services:
  - type: cron
    name: search-channels
    runtime: node
    region: singapore
    plan: 0.5c-512mb
    buildCommand: npm install
    startCommand: npm run collect
    schedule: "17 */3 * * *"
    autoDeployTrigger: commit
    envVars:
      - key: NODE_ENV
        value: production
      - key: GITHUB_OWNER
        value: masum8miah-cpu
      - key: TARGET_REPO
        value: my-ip-tv
      - key: TARGET_BRANCH
        value: main
      - key: SOURCE_PLAYLIST
        value: Brightis.m3u
      - key: SEARCH_OUTPUT
        value: সার্চ কালেকশন.m3u
      - key: LIVE_OUTPUT
        value: live-event-channel-colector.m3u
      - key: FIRECRAWL_ENABLED
        value: "true"
      - key: FIRECRAWL_API_KEY
        sync: false
      - key: FIRECRAWL_RESULTS
        value: "5"
      - key: DDG_ENABLED
        value: "true"
      - key: MIN_WEB_RESULTS
        value: "3"
      - key: GOOGLE_ENABLED
        value: "false"
      - key: GITHUB_ENABLED
        value: "true"
      - key: GITHUB_TOKEN
        sync: false
